version: "3"

services:

    nginx:
        container_name: nginx
        build: ./requirments/nginx/
        image: nginx
        restart: always
        volumes:
            - wordpress_volume:/var/www/wordpress
        depends_on:
            - wordpress
        networks:
            - inception_network
        ports:
            - 80:80
            - 443:443

    wordpress:
        container_name: wordpress
        build: 
            context: ./requirments/wordpress/
            dockerfile: Dockerfile
            args:
                MYSQL_ADMIN_USERNAME: ${MYSQL_ADMIN_USERNAME}
                MYSQL_ADMIN_PASSWORD: ${MYSQL_ADMIN_PASSWORD}
                WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
        environment:
            MYSQL_ADMIN_USERNAME: ${MYSQL_ADMIN_USERNAME}
            MYSQL_ADMIN_PASSWORD: ${MYSQL_ADMIN_PASSWORD}
            WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
        image: wordpress
        restart: always
        volumes:
            - wordpress_volume:/var/www/wordpress 
        depends_on:
            - mariadb 
        networks:
            - inception_network
        expose:
            - 9000

    mariadb:
        container_name: mariadb
        build: 
            context: ./requirments/mariadb/
            dockerfile: Dockerfile
            args:
                MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
                MYSQL_ADMIN_USERNAME: ${MYSQL_ADMIN_USERNAME}
                MYSQL_ADMIN_PASSWORD: ${MYSQL_ADMIN_PASSWORD}
                WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
        image: mariadb
        restart: always
        volumes:
            - mariadb_volume:/var/lib/mysql
        networks:
            - inception_network
        expose:
            - 3306

networks:
    inception_network:
        driver: bridge

volumes:
    mariadb_volume:
        driver_opts:
            type: none
            device: ${MARIADB_VOLUME}
            o: bind

    wordpress_volume:
        driver_opts:
            type: none
            device: ${WORDPRESS_VOLUME} 
            o: bind
